### ISSUE TITLE
Slack Hook is failing with a null commit message

### ISSUE THREAD

**Issue by mwren-mshanken** [sorry-cypress/sorry-cypress#329]
## Summary

I am seeing an error during my Slack Hook execution.

From AWS Cloudwatch:

```
I’m getting an error executing a slack hook on rc8

(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null

at reportToSlack (/app/packages/director/dist/lib/hooks/reporters/slack.js:60:75)
at /app/packages/director/dist/lib/hooks/reporters/controller.js:33:34
at Array.forEach (<anonymous>)
at reportToHook (/app/packages/director/dist/lib/hooks/reporters/controller.js:31:20)
at EventEmitter.<anonymous> (/app/packages/director/dist/lib/hooks/init.js:23:32)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by...
``` 

I don’t have a branch defined in my slack hook
My codebuild also pulls in a secondary git source. Wondering if this is an issue?
The codePipeline I am running Cypress from pulls in two sources, builds both separately, deploys both separately, then executes Cypress codeBuilds in parallel after the deploy step.

## How to reproduce

I don't have a branch set in my Slack hook. 
I'm also defining a secondary source into my cypress codeBuild project
I'm also running in a pipeline that pulls from 3 separate sources

I'm guessing that the multiple sources may have something to do with this.

FWIW I haven't had my commit info appear on the dashboard since upgrading to beta10, or here on rc8

![image](https://user-images.githubusercontent.com/58752843/116138962-54014880-a68a-11eb-8762-14156cf11d34.png)

I am guessing that one of these things is the root cause?

## Environment

- sorry-cypress version: `v1.0.0-rc.8`
- cypress version: `4.1.0`
- platform: `aws`
- service: `director`

**Comment by mwren-mshanken** [comment]
Looks like #328 probably addresses this!
