### ISSUE TITLE
director yarn test fails

### ISSUE THREAD

**Issue by ee-dev-2020** [sorry-cypress/sorry-cypress#393]
Hi,
Thanks for building making this great alternative solution to cypress dashboard. I'm testing this tool as a potential solution to parallelizing our tests. My company requires the build pipeline to have a test stage and I'm leveraging `yarn test` for that purpose.
However, it looks like there are 2 tests with errors under the packages/director folder:

```
 FAIL  src/lib/hooks/reporters/__tests__/slack.test.ts
  Test suite failed to run

    Jest encountered an unexpected token

...

    Details:

    ../packages/director/src/lib/hooks/reporters/slack.ts:23
      if (!shouldReportSlackHook(event.eventType, hook, event.runSummary, event.run.meta.commit?.branch)) {
                                                                                                ^

    SyntaxError: Unexpected token '.'

      1 | import { HookEvent, RunSummary, SlackHook } from '@sorry-cypress/common';
    > 2 | import {
        | ^
      3 |   isSlackBranchFilterPassed,
      4 |   isSlackEventFilterPassed,
      5 |   isSlackResultFilterPassed,

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1258:14)
      at Object.<anonymous> (src/lib/hooks/reporters/__tests__/slack.test.ts:2:1)
```
```
 FAIL  src/lib/hooks/__tests__/hooksReporter.test.ts
  Test suite failed to run

    Jest encountered an unexpected token
...
    Details:

    .../packages/director/src/config.ts:32
    const INACTIVITY_TIMEOUT_SECONDS = Number(process.env.INACTIVITY_TIMEOUT_SECONDS ?? 180);
                                                                                      ^

    SyntaxError: Unexpected token '?'

       7 |   RunWithSpecs,
       8 | } from '@sorry-cypress/common';
    >  9 | import { APP_NAME } from '@src/config';
         | ^
      10 | import { getDashboardRunURL } from '@src/lib/urls';
      11 | import axios from 'axios';
      12 | import md5 from 'md5';

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1258:14)
      at Object.<anonymous> (src/lib/hooks/reporters/bitbucket.ts:9:1)
```
```
Test Suites: 2 failed, 2 passed, 4 total
Tests:       24 passed, 24 total
Snapshots:   0 total
Time:        2.342s
Ran all test suites.
```

I have omitted some of the console output to focus on the actual issues. 
Is this a known error? or am I missing something prior to executing the tests?.  I understand if this is not a priority but would love to hear if there is a way to fix the errors.

- Edison

**Comment by agoldis** [comment]
@ee-dev-2020 we are really lacking good tests, unfortunately. Hopefully that situation will change in future. Please check out our automated GH actions setup https://github.com/sorry-cypress/sorry-cypress/runs/2837877826?check_suite_focus=true - it runs tests on every push, should be similar to any other CI environment
