### ISSUE TITLE
`BSONObjectTooLarge` in director logs

### ISSUE THREAD

**Issue by nazarewk** [sorry-cypress/sorry-cypress#502]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [ ] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary
I'm seeing a lot of `BSONObjectTooLarge` errors in Director/MongoDB. I don't have much idea about why or when the errors are thrown.

## How to reproduce

??

## Relevant logs / screenshots

MongoDB (this is a Datadog monitoring entry):
```
{
"c": "-",
"attr": {
	"line": 101,
	"file": "src/mongo/bson/bsonobj.cpp",
	"error": "BSONObjectTooLarge: BSONObj size: 22711203 (0x15A8BA3) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: ObjectId('61b1078a5239530ff74ee80a')"
},
"ctx": "conn21102",
"s": "E",
"t": {
	"$date": "2021-12-08T19:59:51.997+00:00"
},
"id": 23077
}
```
And a Director log entries:
```
Dec 08 20:59:52.743	sorry-cypress-director	(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5398)
Dec 08 20:59:52.743	sorry-cypress-director	at readableAddChunk (internal/streams/readable.js:265:9)
Dec 08 20:59:52.743	sorry-cypress-director	at addChunk (internal/streams/readable.js:290:12)
Dec 08 20:59:52.743	sorry-cypress-director	at Socket.emit (events.js:400:28)
Dec 08 20:59:52.743	sorry-cypress-director	at Socket.ondata (internal/streams/readable.js:726:22)
Dec 08 20:59:52.743	sorry-cypress-director	at MessageStream.Writable.write (internal/streams/writable.js:303:10)
Dec 08 20:59:52.743	sorry-cypress-director	at writeOrBuffer (internal/streams/writable.js:358:12)
Dec 08 20:59:52.743	sorry-cypress-director	at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
Dec 08 20:59:52.743	sorry-cypress-director	at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
Dec 08 20:59:52.743	sorry-cypress-director	at MessageStream.emit (events.js:400:28)
Dec 08 20:59:52.743	sorry-cypress-director	at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:272:20)
Dec 08 20:59:52.743	sorry-cypress-director	(node:1) UnhandledPromiseRejectionWarning: MongoError: BSONObj size: 22711203 (0x15A8BA3) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: ObjectId('61b1078a5239530ff74ee80a')
```

## Environment

- sorry-cypress version: `1.1.1`
- cypress version: `8.7.0`
- platform: `kubernetes`
- service: `director`

**Comment by agoldis** [comment]
Thanks for reporting that! The issue was resolved in v2 if you have a chance, please upgrade
