### ISSUE TITLE
We encountered an unexpected error talking to our servers. StatusCodeError: 400 - "Must provide query string."

### ISSUE THREAD

**Issue by davidcorbin** [sorry-cypress/sorry-cypress#551]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [x] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

Sorry cypress does gets a 400 error on the client side saying `We encountered an unexpected error talking to our servers.`, but should start a normal cypress run.

## How to reproduce

1. In this case, I deployed the helm chart to a kubernetes cluster although I'm not sure this is kubernetes specific

  ```
    helm install sorry-cypress sorry-cypress/sorry-cypress \
      --set api.ingress.hosts\[0\].host="api.sorry-cypress.tools.davcor.co" \
      --set api.ingress.ingressClassName="" \
      --set api.image.tag="2.1.1" \
      --set dashboard.ingress.ingressClassName="" \
      --set dashboard.ingress.hosts\[0\].host="sorry-cypress.tools.davcor.co" \
      --set dashboard.environmentVariables.graphQlSchemaUrl="http://api.sorry-cypress.tools.davcor.co" \
      --set dashboard.image.tag="2.1.1" \
      --set director.ingress.ingressClassName="" \
      --set director.ingress.hosts\[0\].host="director.sorry-cypress.tools.davcor.co" \
      --set director.environmentVariables.executionDriver="../execution/mongo/driver" \
      --set director.environmentVariables.screenshotsDriver="../screenshots/s3.driver" \
      --set director.image.tag="2.1.1" \
      --set minio.enabled=true \
      --set minio.endpoint=storage.sorry-cypress.tools.davcor.co \
      --set minio.url=http://storage.sorry-cypress.tools.davcor.co \
      --set runCleaner.enabled=true
```

3. `DEBUG=cypress:* npx cy2 run --record --key test --parallel --ci-build-id "local1" --spec "cypress/integration/mockedTests/**/*"`

## Relevant logs / screenshots

- Please submit relevant logs from `DEBUG=cypress:server:api cy2 ....`

```
  cypress:network:agent addRequest called { isHttps: false, href: 'http://api.sorry-cypress.tools.davcor.co/runs' } +0ms
  cypress:network:connect beginning getAddress { hostname: 'api.sorry-cypress.tools.davcor.co', port: 80 } +3s
  cypress:network:connect got addresses { hostname: 'api.sorry-cypress.tools.davcor.co', port: 80, addresses: [ { address: '10.230.128.189', family: 4 } ] } +2ms
  cypress:network:agent got family { family: 4, href: 'http://api.sorry-cypress.tools.davcor.co/runs' } +14ms
  cypress:server:record failed creating run with status 400 { stack: 'StatusCodeError: 400 - "Must provide query string."\n' + '    at new StatusCodeError (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/node_modules/request-promise-core/lib/errors.js:32:15)\n' + '    at Request.plumbing.callback (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/node_modules/request-promise-core/lib/plumbing.js:104:33)\n' + '    at Request.RP$callback [as _callback] (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/node_modules/request-promise-core/lib/plumbing.js:46:31)\n' + '    at Request.self.callback (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/node_modules/@cypress/request/request.js:183:22)\n' + '    at Request.emit (node:events:394:28)\n' + '    at Request.<anonymous> (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/node_modules/@cypress/request/request.js:1156:10)\n' + '    at Request.emit (node:events:394:28)\n' + '    at IncomingMessage.<anonymous> (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/node_modules/@cypress/request/request.js:1070:12)\n' + '    at Object.onceWrapper (node:events:513:28)\n' + '    at IncomingMessage.emit (node:events:406:35)\n' + '    at endReadableNT (node:internal/streams/readable:1331:12)\n' + '    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n' } +0ms
  cypress:server:cypress exiting with err Error: We encountered an unexpected error talking to our servers.

Because you passed the --parallel flag, this run cannot proceed because it requires a valid response from our servers.

The --ciBuildId flag you passed was: local1

The server's response was:

StatusCodeError: 400 - "Must provide query string."
    at Object.get (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:1043:15)
    at throwDashboardCannotProceed (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/modes/record.js:60:29)
    at /Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/modes/record.js:522:9
    at tryCatcher (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/rWe encountered an unexpected error talking to our servers.

Because you passed the --parallel flag, this run cannot proceed because it requires a valid response from our servers.

The --ciBuildId flag you passed was: local1

The server's response was:

StatusCodeError: 400 - "Must provide query string."
elease/async.js:86:9)
    at Async._drainQueues (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/dks0525302/Library/Caches/Cypress/9.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)
 {
  isCypressErr: true,
  type: 'DASHBOARD_CANNOT_PROCEED_IN_PARALLEL',
  details: undefined,
  isFatalApiErr: true
} +5s
  cypress:server:cypress calling exit 1 +1ms
  cypress:server:cypress about to exit with code 1 +0ms
  cypress:server:browsers browsers.kill called with no active instance +3s
  cypress:proxy:http:util:prerequests metrics: { browserPreRequestsReceived: 0, proxyRequestsReceived: 0, immediatelyMatchedRequests: 0, eventuallyReceivedPreRequest: [], neverReceivedPreRequest: [] } +0ms
  cypress:cli child event fired { event: 'exit', code: 1, signal: null } +8s
```

- Please submit relevant logs from director / api / dahsboard service

There are surprisingly few log in the API and director. Just the startup logs but nothing related to requests. 

- Please submit screenshots if relevant

## Environment

- sorry-cypress version: 2.1.1
- cypress version: `9.4.1`
- platform: `kubernetes`
- service: `api`

**Comment by agoldis** [comment]
@davidcorbin Are you using director service as `CYPRESS_API_URL`? That's a bit confusing probably, but you're supposed to use director service and not api.
