### ISSUE TITLE
Off-by-one error in sorry-cypress causes browser to be closed prematurely in Cypress >=10

### ISSUE THREAD

**Issue by alyssa-glean** [sorry-cypress/sorry-cypress#613]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [ ] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio - N/A
- [ ] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error - N/A

## Summary

When using the `sorry-cypress` director, there is an off-by-one error in the test index that's reported in the logging. The first spec gets labelled "2 of N", and this continues right up until the final spec which gets reported as "N+1 of N". Until Cypress 10, this was just an inconsequential quirk, but is now causing actual problems for us having bumped to Cypress 10.3.0.

Previously, Cypress used to launch a new browser per test spec. As of Cypress 10, though, it launches one browser at the start of the run and opens a new tab for each new spec (see [this issue comment](https://github.com/cypress-io/cypress/issues/2951#issuecomment-1188491798)). I believe that it then closes the browser when the "last" spec has been run.

What this means in practice is that if a runner picks up the two final specs of a run, you end up with an error. After it runs the first of these the browser is closed (because sorry-cypress says that it's e.g. "18 of 18"). The final spec then tries to run, and errors out because the browser is no longer available.

N.B. I found this issue which is the same thing: https://github.com/sorry-cypress/sorry-cypress/issues/543. However, the title is misleading as to what's actually happening, and it was closed for inactivity. So I thought it best to raise a new issue.

## How to reproduce

I can replicate this 100% of the time by using `sorry-cypress` with a single runner and Cypress 10.3.0. With multiple runners it only happens sometimes (because runs where specs N-1 and N are picked up by different runners are unaffected). Taking `sorry-cypress` out of the equation removes the problem entirely.

## Relevant logs / screenshots

See the following logs from the end of a run using a single runner and sorry-cypress, showing the final two specs and what happens:

```
[2022-08-03T16:02:26.477Z] ────────────────────────────────────────────────────────────────────────────────────────────────────
[2022-08-03T16:02:26.477Z]                                                                                                     
[2022-08-03T16:02:26.477Z]   Running:  readingViewScreenshot.spec.ts                                                 (17 of 17)
[2022-08-03T16:02:28.358Z] 
[2022-08-03T16:02:28.358Z] 
[2022-08-03T16:02:28.358Z]   reading view screenshot
[2022-08-03T16:02:36.425Z] Succeeded, so deleting successful output
[2022-08-03T16:02:37.349Z] Succeeded, so deleting successful output
[2022-08-03T16:02:42.581Z] Succeeded, so deleting successful output
[2022-08-03T16:02:43.505Z] Succeeded, so deleting successful output
[2022-08-03T16:02:43.505Z]     ✓ view event in reading view and compare screenshot (15227ms)
[2022-08-03T16:04:19.906Z] Succeeded, so deleting successful output
[2022-08-03T16:04:19.907Z] Succeeded, so deleting successful output
[2022-08-03T16:04:19.907Z]     ✓ view event with images in reading view and compare screenshot (89849ms)
[2022-08-03T16:04:20.485Z] Succeeded, so deleting successful output
[2022-08-03T16:04:22.368Z] Succeeded, so deleting successful output
[2022-08-03T16:04:22.368Z]     ✓ view event with large image in reading view and compare screenshot (8510ms)
[2022-08-03T16:04:22.368Z] 
[2022-08-03T16:04:22.368Z] 
[2022-08-03T16:04:22.368Z]   3 passing (2m)
[2022-08-03T16:04:22.368Z] 
[2022-08-03T16:04:23.291Z] Posting successful run of 'integration/screenshots/readingViewScreenshot.spec.ts' to Redis 'passing-e2e-specs:f73e646d3f1793216461dd0050788badc6798ca6'
[2022-08-03T16:04:23.291Z] 
[2022-08-03T16:04:23.291Z]   (Results)
[2022-08-03T16:04:23.291Z] 
[2022-08-03T16:04:23.292Z]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[2022-08-03T16:04:23.292Z]   │ Tests:        3                                                                                │
[2022-08-03T16:04:23.292Z]   │ Passing:      3                                                                                │
[2022-08-03T16:04:23.292Z]   │ Failing:      0                                                                                │
[2022-08-03T16:04:23.292Z]   │ Pending:      0                                                                                │
[2022-08-03T16:04:23.292Z]   │ Skipped:      0                                                                                │
[2022-08-03T16:04:23.292Z]   │ Screenshots:  8                                                                                │
[2022-08-03T16:04:23.292Z]   │ Video:        false                                                                            │
[2022-08-03T16:04:23.292Z]   │ Duration:     1 minute, 53 seconds                                                             │
[2022-08-03T16:04:23.292Z]   │ Spec Ran:     readingViewScreenshot.spec.ts                                                    │
[2022-08-03T16:04:23.293Z]   └────────────────────────────────────────────────────────────────────────────────────────────────┘
[2022-08-03T16:04:23.293Z] 
[2022-08-03T16:04:23.293Z] 
[2022-08-03T16:04:23.293Z]   (Screenshots)
[2022-08-03T16:04:23.293Z] 
[2022-08-03T16:04:23.293Z]   -  /home/jenkins/agent/workspace/glean_solo-screenshots/frontend/testing/e2e/screen     (1000x800)
[2022-08-03T16:04:23.293Z]      shots/readingViewScreenshot.spec.ts/reading-view.png                                           
[2022-08-03T16:04:23.293Z]   -  /home/jenkins/agent/workspace/glean_solo-screenshots/frontend/testing/e2e/screen     (1000x800)
[2022-08-03T16:04:23.293Z]      shots/readingViewScreenshot.spec.ts/reading-view-dark-mode.png                                 
[2022-08-03T16:04:23.293Z]   -  /home/jenkins/agent/workspace/glean_solo-screenshots/frontend/testing/e2e/screen     (1000x800)
[2022-08-03T16:04:23.293Z]      shots/readingViewScreenshot.spec.ts/reading-view-empty.png                                     
[2022-08-03T16:04:23.293Z]   -  /home/jenkins/agent/workspace/glean_solo-screenshots/frontend/testing/e2e/screen     (1000x800)
[2022-08-03T16:04:23.293Z]      shots/readingViewScreenshot.spec.ts/reading-view-empty-dark-mode.png                           
[2022-08-03T16:04:23.293Z]   -  /home/jenkins/agent/workspace/glean_solo-screenshots/frontend/testing/e2e/screen     (1000x800)
[2022-08-03T16:04:23.293Z]      shots/readingViewScreenshot.spec.ts/reading-view-with-images.png                               
[2022-08-03T16:04:23.293Z]   -  /home/jenkins/agent/workspace/glean_solo-screenshots/frontend/testing/e2e/screen     (1000x800)
[2022-08-03T16:04:23.293Z]      shots/readingViewScreenshot.spec.ts/reading-view-with-images-dark-mode.png                     
[2022-08-03T16:04:23.293Z]   -  /home/jenkins/agent/workspace/glean_solo-screenshots/frontend/testing/e2e/screen     (1000x800)
[2022-08-03T16:04:23.293Z]      shots/readingViewScreenshot.spec.ts/reading-view-with-large-image.png                          
[2022-08-03T16:04:23.293Z]   -  /home/jenkins/agent/workspace/glean_solo-screenshots/frontend/testing/e2e/screen     (1000x800)
[2022-08-03T16:04:23.293Z]      shots/readingViewScreenshot.spec.ts/reading-view-with-large-image-dark-mode.png                
[2022-08-03T16:04:23.293Z] 
[2022-08-03T16:04:23.293Z] 
[2022-08-03T16:04:23.293Z]   (Uploading Results)
[2022-08-03T16:04:23.293Z] 
[2022-08-03T16:04:23.293Z]   - Nothing to Upload
[2022-08-03T16:04:23.293Z] 
[2022-08-03T16:04:23.294Z] ────────────────────────────────────────────────────────────────────────────────────────────────────
[2022-08-03T16:04:23.294Z]                                                                                                     
[2022-08-03T16:04:23.294Z]   Running:  searchScreenshot.spec.ts                                                      (18 of 17)
[2022-08-03T16:05:30.883Z] 
[2022-08-03T16:05:30.883Z] Timed out waiting for the browser to connect. Retrying...
[2022-08-03T16:06:27.015Z] 
[2022-08-03T16:06:27.015Z] Timed out waiting for the browser to connect. Retrying again...
[2022-08-03T16:07:23.148Z] 
[2022-08-03T16:07:23.148Z] The browser never connected. Something is wrong. The tests cannot run. Aborting...
[2022-08-03T16:07:23.148Z] 
[2022-08-03T16:07:23.148Z] The browser never connected. Something is wrong. The tests cannot run. Aborting...
[2022-08-03T16:07:27.301Z] Warning: We failed processing this video.
[2022-08-03T16:07:27.301Z] 
[2022-08-03T16:07:27.301Z] This error will not alter the exit code.
[2022-08-03T16:07:27.301Z] 
[2022-08-03T16:07:27.301Z] TimeoutError: operation timed out
[2022-08-03T16:07:27.301Z]     at afterTimeout (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/timers.js:46:19)
[2022-08-03T16:07:27.301Z]     at Timeout.timeoutTimeout [as _onTimeout] (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/timers.js:76:13)
[2022-08-03T16:07:27.301Z]     at listOnTimeout (node:internal/timers:557:17)
[2022-08-03T16:07:27.301Z]     at processTimers (node:internal/timers:500:7)
[2022-08-03T16:07:27.301Z] 
[2022-08-03T16:07:27.301Z] 
[2022-08-03T16:07:27.302Z]   (Results)
[2022-08-03T16:07:27.302Z] 
[2022-08-03T16:07:27.302Z]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[2022-08-03T16:07:27.302Z]   │ Tests:        0                                                                                │
[2022-08-03T16:07:27.302Z]   │ Passing:      0                                                                                │
[2022-08-03T16:07:27.302Z]   │ Failing:      1                                                                                │
[2022-08-03T16:07:27.302Z]   │ Pending:      0                                                                                │
[2022-08-03T16:07:27.302Z]   │ Skipped:      0                                                                                │
[2022-08-03T16:07:27.302Z]   │ Screenshots:  0                                                                                │
[2022-08-03T16:07:27.302Z]   │ Video:        false                                                                            │
[2022-08-03T16:07:27.302Z]   │ Duration:     0 seconds                                                                        │
[2022-08-03T16:07:27.302Z]   │ Spec Ran:     searchScreenshot.spec.ts                                                         │
[2022-08-03T16:07:27.303Z]   └────────────────────────────────────────────────────────────────────────────────────────────────┘
[2022-08-03T16:07:27.303Z] 
[2022-08-03T16:07:27.303Z] Could not process 'reset:browser:tabs:for:next:test'. No automation clients connected.
[2022-08-03T16:07:27.303Z] Error: Could not process 'reset:browser:tabs:for:next:test'. No automation clients connected.
[2022-08-03T16:07:27.303Z]     at SocketE2E.onAutomation (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/lib/socket-base.js:88:15)
[2022-08-03T16:07:27.303Z]     at onAutomationClientRequestCallback (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/lib/socket-base.js:134:25)
[2022-08-03T16:07:27.303Z]     at /root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/lib/automation/automation.js:77:20
[2022-08-03T16:07:27.303Z]     at Promise.cancellationExecute [as _execute] (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/debuggability.js:406:9)
[2022-08-03T16:07:27.303Z]     at Promise._resolveFromExecutor (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:518:18)
[2022-08-03T16:07:27.303Z]     at new Promise (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:103:10)
[2022-08-03T16:07:27.303Z]     at Automation.requestAutomationResponse (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/lib/automation/automation.js:62:16)
[2022-08-03T16:07:27.303Z]     at /root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/lib/automation/automation.js:58:52
[2022-08-03T16:07:27.303Z]     at /root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/lib/automation/automation.js:122:28
[2022-08-03T16:07:27.303Z]     at tryCatcher (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
[2022-08-03T16:07:27.303Z]     at Function.Promise.attempt.Promise.try (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
[2022-08-03T16:07:27.303Z]     at Automation.normalize (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/lib/automation/automation.js:90:38)
[2022-08-03T16:07:27.303Z]     at /root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/lib/automation/automation.js:153:25
[2022-08-03T16:07:27.303Z]     at tryCatcher (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
[2022-08-03T16:07:27.303Z]     at Promise._settlePromiseFromHandler (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
[2022-08-03T16:07:27.304Z]     at Promise._settlePromise (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
[2022-08-03T16:07:27.304Z]     at Promise._settlePromiseCtx (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:641:10)
[2022-08-03T16:07:27.304Z]     at _drainQueueStep (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:97:12)
[2022-08-03T16:07:27.304Z]     at _drainQueue (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
[2022-08-03T16:07:27.304Z]     at Async._drainQueues (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
[2022-08-03T16:07:27.304Z]     at Immediate.Async.drainQueues [as _onImmediate] (/root/.cache/Cypress/10.3.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
[2022-08-03T16:07:27.304Z]     at processImmediate (node:internal/timers:464:21)
[2022-08-03T16:07:27.304Z] 
script returned exit code 1
```

## Environment

- sorry-cypress version: `2.2.1`
- cypress version: `10.3.0`
- platform: `GKE`
- service: `director`

**Comment by alyssa-glean** [comment]
I believe [this line](https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/director/src/execution/in-memory.ts#L162) may be the culprit, I'm going to have a go at doing a PR to resolve this.
