### ISSUE TITLE
Regression in v2.3.2 when parsing remote origin URL

### ISSUE THREAD

**Issue by anlambert** [sorry-cypress/sorry-cypress#636]
## Summary

Commit https://github.com/sorry-cypress/sorry-cypress/commit/60abceedf16abc6f6bd8ef83fe6189a450e68eb8 modified the `getRemoteOrigin` function (see [diff](https://github.com/sorry-cypress/sorry-cypress/commit/60abceedf16abc6f6bd8ef83fe6189a450e68eb8#diff-d4994e429e2edb06c7d64bff36c3a4fe113cb220f96c45c71d54edcbdd77b425R40)) but that code considers that every remote origin URL has a `@` character in it. However numerous projects use a remote origin URL in the form `https://git.example.org/user/project[.git]` so the `getRemoteOrigin` function now raises an error when attempting to parse such URLs and thus cypress tests are not executed.

## How to reproduce

1. Clone a git project with cypress tests from an URL without '@' character in it
2. Follow the `sorry-cypress` guide to run tests in parallel => error at sorry-cypress startup

## Relevant logs / screenshots

Below is the output when attempting to start tests for a project whose remote origin URL is https://forge.softwareheritage.org/source/swh-web.git

```
(swh) ✘-INT ~/swh/swh-environment/swh-web [cypress-parallel-tests L|⚑ 151] 
13:28 $ CYPRESS_API_URL="http://localhost:1234/" yarn run cy2 run --record --key swh-web --parallel --config baseUrl=http://localhost:5004 --ci-build-id swh-web-1
yarn run v1.22.19
$ /home/anlambert/swh/swh-environment/swh-web/node_modules/.bin/cy2 run --record --key swh-web --parallel --config baseUrl=http://localhost:5004 --ci-build-id swh-web-1
[cy2] Running cypress with API URL: http://localhost:1234/
We encountered an unexpected error talking to our servers.

We will retry 3 more times in 30 seconds...

The server's response was:

StatusCodeError: 500 - "Unexpected error from sorry-cypress director service. Check the service logs for details."
We encountered an unexpected error talking to our servers.

We will retry 2 more times in 1 minute...

The server's response was:

StatusCodeError: 500 - "Unexpected error from sorry-cypress director service. Check the service logs for details."
We encountered an unexpected error talking to our servers.

We will retry 1 more time in 2 minutes...

The server's response was:

StatusCodeError: 500 - "Unexpected error from sorry-cypress director service. Check the service logs for details."
We encountered an unexpected error talking to our servers.

We will retry 0 more times in ...

The server's response was:

StatusCodeError: 500 - "Unexpected error from sorry-cypress director service. Check the service logs for details."
We encountered an unexpected error talking to our servers.

Because you passed the --parallel flag, this run cannot proceed because it requires a valid response from our servers.

The --ciBuildId flag you passed was: swh-web-1

The server's response was:

StatusCodeError: 500 - "Unexpected error from sorry-cypress director service. Check the service logs for details."
```

Below are the relevant error logs from the `sorry-cypress` server.

```json
{
   "level":50,
   "time":1661772724420,
   "requestId":"19a9e805-4638-4e36-bea4-2ddeadfeb364",
   "error":{
      "type":"TypeError",
      "message":"Cannot read property 'replace' of undefined",
      "stack":"TypeError: Cannot read property 'replace' of undefined\n    at getRemoteOrigin (/app/packages/director/src/execution/utils.ts:40:23)\n    at Object.createRun (/app/packages/director/src/execution/in-memory.ts:106:32)\n    at handleCreateRun (/app/packages/director/src/api/runs.ts:33:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at /app/packages/director/src/lib/express.ts:10:5"
   }
}
```

```json
{
   "level":30,
   "time":1661772724421,
   "req":{
      "id":5,
      "method":"POST",
      "url":"/runs",
      "query":{
         
      },
      "params":{
         
      },
      "headers":{
         "x-route-version":"4",
         "x-cypress-request-attempt":"4",
         "x-os-name":"linux",
         "x-cypress-version":"10.6.0",
         "host":"localhost:1234",
         "accept-encoding":"gzip, deflate",
         "accept":"application/json",
         "content-type":"application/json",
         "content-length":"2834",
         "connection":"close"
      },
      "remoteAddress":"::ffff:172.17.0.1",
      "remotePort":35942
   },
   "res":{
      "statusCode":500,
      "headers":{
         "x-powered-by":"Express",
         "content-type":"text/html; charset=utf-8",
         "content-length":"89",
         "etag":"W/\"59-JMJsr+GKg9vLr9EtbregGDl0ppM\""
      }
   },
   "err":{
      "type":"Error",
      "message":"failed with status code 500",
      "stack":"Error: failed with status code 500\n    at ServerResponse.onResFinished (/app/node_modules/pino-http/logger.js:74:38)\n    at ServerResponse.emit (events.js:412:35)\n    at onFinish (_http_outgoing.js:792:10)\n    at callback (internal/streams/writable.js:513:21)\n    at afterWrite (internal/streams/writable.js:466:5)\n    at afterWriteTick (internal/streams/writable.js:453:10)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"
   },
   "responseTime":3,
   "msg":"request errored"
}
```

## Environment

- sorry-cypress version: `v2.3.2`
- cypress version: `10.6.0`
- platform: `docker`
- service: `director`

**Comment by karolkujaw** [comment]
Reproducible for me as well - just retry with the `2.3.1` version instead of the `latest`

**Comment by bjartur20** [comment]
I'm working on a PR to fix this.
