### ISSUE TITLE
Dashboard cannot access failure screenshot and video when using docker-compose.minio.yml 

### ISSUE THREAD

**Issue by chaowakrit** [sorry-cypress/sorry-cypress#667]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [ ] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

The sorry-cypress cannot access failure screenshot and video, but when I look at MinIO console, it exists 

## How to reproduce

1. Add minio console port and binding  port docker-compose.minio.yml 
```
version: '3.6'

services:
  mongo:
    image: mongo:4.4
    volumes:
      - ./data/data-mongo-cypress:/data/db
    ports:
      - 27017:27017
  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: http://localhost:8080
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'

      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      GITLAB_JOB_RETRIES: 'false'
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
      MINIO_ENDPOINT: 'localhost'
      MINIO_URL: 'http://localhost'
      MINIO_PORT: '9000'
      MINIO_USESSL: 'false'
      MINIO_BUCKET: sorry-cypress

    ports:
      - 1234:1234
      - 9000:9000
      - 9090:9090
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'false'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://localhost:4000
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: 8080
      CI_URL: ''
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api

  storage:
    image: minio/minio
    network_mode: service:director
    environment:
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
    volumes:
      - ./data/data-minio-cypress:/data
    command: server --console-address :9090 /data

  createbuckets:
    image: minio/mc
    network_mode: service:director
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add myminio http://localhost:9000 MW32h3gd6HvjBEgTRx t6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7;
      /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
      /usr/bin/mc mb myminio/sorry-cypress;
      /usr/bin/mc policy set download myminio/sorry-cypress;
      /usr/bin/mc policy set public myminio/sorry-cypress;
      exit 0;
      "
```
2. Run docker compose up
3. Start failure test
4. Click failure image link in Dashboard

## Relevant logs / screenshots

```
2022-10-11T03:57:07.425Z cypress:server:api request to url: POST http://localhost:1234/instances/802e076f-9039-49d0-b9c3-9d8ca1e3bf2f/results with params: {"body":{"stats":{"suites":1,"tests":3,"passes":2,"pending":0,"skipped":0,"failures":1,"wallClockStartedAt":"2022-10-11T03:55:22.327Z","wallClockEndedAt":"2022-10-11T03:56:59.772Z","wallClockDuration":97445},"tests":[{"clientId":"r3","state":"passed","displayError":null,"attempts":[{"state":"passed","error":null,"timings":{"lifecycle":6,"before each":[{"hookId":"h1","fnDuration":9427,"afterFnDuration":0}],"test":{"fnDuration":33528,"afterFnDuration":0}},"failedFromHookId":null,"wallClockStartedAt":"2022-10-11T03:55:23.748Z","wallClockDuration":42967,"videoTimestamp":3121}]},{"clientId":"r4","state":"failed","displayError":"AssertionError: Timed out retrying after 4000ms: expected '<input#email_auth>' to have value 'anuchit@thinknet.co.th', but the value was 'test.tnuser02+company@gmail.com'\n    at Context.eval (webpack:///./cypress/e2e/comLogin/companyLogin.cy.js:76:42)","attempts":[{"state":"failed","error":{"name":"AssertionError","message":"Timed out retrying after 4000ms: expected '<input#email_auth>' to have value 'anuchit@thinknet.co.th', but the value was 'test.tnuser02+company@gmail.com'","stack":"    at Context.eval (webpack:///./cypress/e2e/comLogin/companyLogin.cy.js:76:42)","codeFrame":{"line":76,"column":43,"originalFile":"cypress/e2e/comLogin/companyLogin.cy.js","relativeFile":"cypress/e2e/comLogin/companyLogin.cy.js","absoluteFile":"/Users/chaowakrit/Workspace/JobThai/web-jtu-system/cypress/e2e/comLogin/companyLogin.cy.js","frame":"  74 |     }\n  75 |     cy.get(ELEMENT_JOBTHAI.COMPANY_NAME).should('have.value', 'บริษัท แสนแสบ จำกัด') // Company Name\n> 76 |     cy.get(ELEMENT_JOBTHAI.EMAIL_ACCOUNT).should('have.value', 'anuchit@thinknet.co.th') // Email Auth\n     |                                           ^\n  77 |     cy.newTab(ELEMENT_JOBTHAI.LOGO_JOBTHAI)\n  78 |     cy.location('pathname').then((pathname) => decodeURIComponent(pathname)).should('eq', t('companyLogin.URL.HOME'))\n  79 |     cy.get(ELEMENT_JOBTHAI.H_MENU_EMPLOYER).should('contain', `${t('companyLogin.ELEMENT_JOBTHAI.H_MENU_EMPLOYER')} (testuserjtm)`)// .click()","language":"js"}},"timings":{"lifecycle":55,"before each":[{"hookId":"h1","fnDuration":6958,"afterFnDuration":0}],"test":{"fnDuration":21717,"afterFnDuration":129}},"failedFromHookId":null,"wallClockStartedAt":"2022-10-11T03:56:06.733Z","wallClockDuration":28863,"videoTimestamp":46106}]},{"clientId":"r5","state":"passed","displayError":null,"attempts":[{"state":"passed","error":null,"timings":{"lifecycle":42,"before each":[{"hookId":"h1","fnDuration":5766,"afterFnDuration":0}],"test":{"fnDuration":18330,"afterFnDuration":0}},"failedFromHookId":null,"wallClockStartedAt":"2022-10-11T03:56:35.620Z","wallClockDuration":24148,"videoTimestamp":74993}]}],"exception":null,"video":true,"screenshots":[{"screenshotId":"y3k1x","name":null,"testId":"r4","testAttemptIndex":0,"takenAt":"2022-10-11T03:56:35.477Z","height":720,"width":1280}],"reporterStats":{"suites":1,"tests":3,"passes":2,"pending":0,"failures":1,"start":"2022-10-11T03:55:22.330Z","end":"2022-10-11T03:56:59.801Z","duration":97471},"metadata":{"studioCreated":0,"studioExtended":0}},"headers":{"x-route-version":"1","x-cypress-request-attempt":0,"x-os-name":"darwin","x-cypress-version":"10.9.0"}} and token: undefined
2022-10-11T03:57:07.511Z cypress:server:api response { screenshotUploadUrls: [ { readUrl: 'http://localhost:9000/sorry-cypress/b32f72c3911426efb9594d5260d7cced.png', uploadUrl: 'http://localhost:9000/sorry-cypress/b32f72c3911426efb9594d5260d7cced.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=MW32h3gd6HvjBEgTRx%2F20221011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221011T035707Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=ca8422550dd23533e0188bc69a2a0a3f13ab5ed21acff570c2461eb57005d9cd', screenshotId: 'y3k1x' } ], videoUploadUrl: 'http://localhost:9000/sorry-cypress/802e076f-9039-49d0-b9c3-9d8ca1e3bf2f.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=MW32h3gd6HvjBEgTRx%2F20221011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221011T035707Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=3e7c55df4bad2c90e3c393290be2fc60ad9624a8fcc5b1cb22f7eeaba993c91c' }
2022-10-11T03:57:07.704Z cypress:server:api request to url: PUT http://localhost:1234/instances/802e076f-9039-49d0-b9c3-9d8ca1e3bf2f/stdout with params: {"body":{"stdout":"\n────────────────────────────────────────────────────────────────────────────────────────────────────\n                                                                                                    \n  Running:  companyLogin.cy.js                                                              (1 of 1)\n\n\n\n\n  TH\n  TH\n    ✓ COM-LOGIN-FORM-01 | Login ด้วย Company Account ครั้งแรก (42962ms)\n    ✓ COM-LOGIN-FORM-01 | Login ด้วย Company Account ครั้งแรก (42962ms)\n    1) COM-LOGIN-FORM-02 | Login ด้วย Company Account เก่า\n    1) COM-LOGIN-FORM-02 | Login ด้วย Company Account เก่า\n    ✓ COM-LOGIN-FORM-03 | Login ด้วย Company Account ใหม่ (24139ms)\n    ✓ COM-LOGIN-FORM-03 | Login ด้วย Company Account ใหม่ (24139ms)\n\n\n\n  2 passing (2m)\n  1 failing\n\n  1) TH\n       COM-LOGIN-FORM-02 | Login ด้วย Company Account เก่า:\n\n      Timed out retrying after 4000ms\n      + expected - actual\n\n      -'test.tnuser02+company@gmail.com'\n      +'anuchit@thinknet.co.th'\n      \n      at Context.eval (webpack:///./cypress/e2e/comLogin/companyLogin.cy.js:76:42)\n\n\n\n\n  2 passing (2m)\n  1 failing\n\n  1) TH\n       COM-LOGIN-FORM-02 | Login ด้วย Company Account เก่า:\n\n      Timed out retrying after 4000ms\n      + expected - actual\n\n      -'test.tnuser02+company@gmail.com'\n      +'anuchit@thinknet.co.th'\n      \n      at Context.eval (webpack:///./cypress/e2e/comLogin/companyLogin.cy.js:76:42)\n\n\n\n[mochawesome] Report JSON saved to /Users/chaowakrit/Workspace/JobThai/web-jtu-system/reports/mochawesome/mochawesome_2022-10-11_10-56-59.json\n\n\n  (Results)\n\n  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐\n  │ Tests:        3                                                                                │\n  │ Passing:      2                                                                                │\n  │ Failing:      1                                                                                │\n  │ Pending:      0                                                                                │\n  │ Skipped:      0                                                                                │\n  │ Screenshots:  1                                                                                │\n  │ Video:        true                                                                             │\n  │ Duration:     1 minute, 37 seconds                                                             │\n  │ Spec Ran:     companyLogin.cy.js                                                               │\n  └────────────────────────────────────────────────────────────────────────────────────────────────┘\n\n\n  (Screenshots)\n\n  -  /Users/chaowakrit/Workspace/JobThai/web-jtu-system/cypress/screenshots/companyLo     (1280x720)\n     gin.cy.js/TH -- COM-LOGIN-FORM-02  Login ด้วย Company Account เก่า (failed).png                \n\n\n  (Video)\n\n  -  Started processing:  Compressing to 32 CRF                                                     \n  -  Finished processing: /Users/chaowakrit/Workspace/JobThai/web-jtu-system/cypress/    (6 seconds)\n                          videos/companyLogin.cy.js.mp4                                             \n\n\n  (Uploading Results)\n\n  - Done Uploading (1/2) /Users/chaowakrit/Workspace/JobThai/web-jtu-system/cypress/screenshots/companyLogin.cy.js/TH -- COM-LOGIN-FORM-02  Login ด้วย Company Account เก่า (failed).png\n  - Done Uploading (2/2) /Users/chaowakrit/Workspace/JobThai/web-jtu-system/cypress/videos/companyLogin.cy.js.mp4\n"},"headers":{"x-cypress-request-attempt":0,"x-os-name":"darwin","x-cypress-version":"10.9.0"}} and token: undefined
2022-10-11T03:57:07.716Z cypress:server:api response 'OK'
2022-10-11T03:57:07.716Z cypress:server:api request to url: POST http://localhost:1234/runs/a37687bfa545382c88837c8f848a2b6d/instances with params: {"body":{"spec":null,"groupId":"test-number-2","machineId":"f05cb56f-a119-479e-8baf-bd356d58bf17","platform":{"osCpus":[{"model":"Apple M1","speed":24,"times":{"user":8530340,"nice":0,"sys":5651600,"idle":41192320,"irq":0}},{"model":"Apple M1","speed":24,"times":{"user":7938260,"nice":0,"sys":5086110,"idle":42348210,"irq":0}},{"model":"Apple M1","speed":24,"times":{"user":7073290,"nice":0,"sys":4443680,"idle":43855640,"irq":0}},{"model":"Apple M1","speed":24,"times":{"user":6369240,"nice":0,"sys":3983550,"idle":45019850,"irq":0}},{"model":"Apple M1","speed":24,"times":{"user":4394320,"nice":0,"sys":1811920,"idle":49166390,"irq":0}},{"model":"Apple M1","speed":24,"times":{"user":3264830,"nice":0,"sys":1240080,"idle":50867700,"irq":0}},{"model":"Apple M1","speed":24,"times":{"user":2546250,"nice":0,"sys":812360,"idle":52014010,"irq":0}},{"model":"Apple M1","speed":24,"times":{"user":2104940,"nice":0,"sys":584830,"idle":52682840,"irq":0}}],"osName":"darwin","osMemory":{"free":158892032,"total":17179869184},"osVersion":"20.3.0","browserName":"Electron","browserVersion":"102.0.5005.148"}},"headers":{"x-route-version":"5","x-cypress-run-id":"a37687bfa545382c88837c8f848a2b6d","x-cypress-request-attempt":0,"x-os-name":"darwin","x-cypress-version":"10.9.0"}} and token: undefined
2022-10-11T03:57:07.738Z cypress:server:api response { spec: null, instanceId: null, claimedInstances: 0, totalInstances: 1 }
```
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15319932/194995053-ad43c89e-1cac-4b42-b379-4fdf8b0d2873.png">
<img width="590" alt="image" src="https://user-images.githubusercontent.com/15319932/194995112-e05d4c76-d4ee-4251-9031-2ac0ce7abf20.png">
<img width="781" alt="image" src="https://user-images.githubusercontent.com/15319932/194995146-d0a2087f-1dcc-4286-9d4d-7a35c4167f79.png">

## Environment

- Mac OSX
- sorry-cypress version: `2.4.2`
- cypress version: `10.9.0`
- platform: `docker`
- service: `dashboard`

**Comment by noskiddie** [comment]
> Please note - issues that are not following the template will be closed automatically:
> 
> * [x]  I have verified that all sorry-cypress services are running and accessible
> * [x]  I have read documentation and found no answer to my problem
> * [x]  I have searched issues / discussions and found to answer to my problem
> * [x]  I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio
> * [ ]  I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error
> 
> ## Summary
> The sorry-cypress cannot access failure screenshot and video, but when I look at MinIO console, it exists
> 
> ## How to reproduce
> 1. Add minio console port and binding  port docker-compose.minio.yml
> 
> ```
> version: '3.6'
> 
> services:
>   mongo:
>     image: mongo:4.4
>     volumes:
>       - ./data/data-mongo-cypress:/data/db
>     ports:
>       - 27017:27017
>   director:
>     image: agoldis/sorry-cypress-director:latest
>     environment:
>       DASHBOARD_URL: http://localhost:8080
>       EXECUTION_DRIVER: '../execution/mongo/driver'
>       MONGODB_URI: 'mongodb://mongo:27017'
>       MONGODB_DATABASE: 'sorry-cypress'
> 
>       SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
>       GITLAB_JOB_RETRIES: 'false'
>       MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
>       MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
>       MINIO_ENDPOINT: 'localhost'
>       MINIO_URL: 'http://localhost'
>       MINIO_PORT: '9000'
>       MINIO_USESSL: 'false'
>       MINIO_BUCKET: sorry-cypress
> 
>     ports:
>       - 1234:1234
>       - 9000:9000
>       - 9090:9090
>     depends_on:
>       - mongo
> 
>   api:
>     image: agoldis/sorry-cypress-api:latest
>     environment:
>       MONGODB_URI: 'mongodb://mongo:27017'
>       MONGODB_DATABASE: 'sorry-cypress'
>       APOLLO_PLAYGROUND: 'false'
>     ports:
>       - 4000:4000
>     depends_on:
>       - mongo
> 
>   dashboard:
>     image: agoldis/sorry-cypress-dashboard:latest
>     environment:
>       GRAPHQL_SCHEMA_URL: http://localhost:4000
>       GRAPHQL_CLIENT_CREDENTIALS: ''
>       PORT: 8080
>       CI_URL: ''
>     ports:
>       - 8080:8080
>     depends_on:
>       - mongo
>       - api
> 
>   storage:
>     image: minio/minio
>     network_mode: service:director
>     environment:
>       MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
>       MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
>     volumes:
>       - ./data/data-minio-cypress:/data
>     command: server --console-address :9090 /data
> 
>   createbuckets:
>     image: minio/mc
>     network_mode: service:director
>     depends_on:
>       - storage
>     entrypoint: >
>       /bin/sh -c "
>       sleep 3;
>       /usr/bin/mc config host add myminio http://localhost:9000 MW32h3gd6HvjBEgTRx t6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7;
>       /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
>       /usr/bin/mc mb myminio/sorry-cypress;
>       /usr/bin/mc policy set download myminio/sorry-cypress;
>       /usr/bin/mc policy set public myminio/sorry-cypress;
>       exit 0;
>       "
> ```
> 
> 2. Run docker compose up
> 3. Start failure test
> 4. Click failure image link in Dashboard
> 
> ## Relevant logs / screenshots
> ```
> 2022-10-11T03:57:07.425Z cypress:server:api request to url: POST http://localhost:1234/instances/802e076f-9039-49d0-b9c3-9d8ca1e3bf2f/results with params: {"body":{"stats":{"suites":1,"tests":3,"passes":2,"pending":0,"skipped":0,"failures":1,"wallClockStartedAt":"2022-10-11T03:55:22.327Z","wallClockEndedAt":"2022-10-11T03:56:59.772Z","wallClockDuration":97445},"tests":[{"clientId":"r3","state":"passed","displayError":null,"attempts":[{"state":"passed","error":null,"timings":{"lifecycle":6,"before each":[{"hookId":"h1","fnDuration":9427,"afterFnDuration":0}],"test":{"fnDuration":33528,"afterFnDuration":0}},"failedFromHookId":null,"wallClockStartedAt":"2022-10-11T03:55:23.748Z","wallClockDuration":42967,"videoTimestamp":3121}]},{"clientId":"r4","state":"failed","displayError":"AssertionError: Timed out retrying after 4000ms: expected '<input#email_auth>' to have value 'anuchit@thinknet.co.th', but the value was 'test.tnuser02+company@gmail.com'\n    at Context.eval (webpack:///./cypress/e2e/comLogin/companyLogin.cy.js:76:42)","attempts":[{"state":"failed","error":{"name":"AssertionError","message":"Timed out retrying after 4000ms: expected '<input#email_auth>' to have value 'anuchit@thinknet.co.th', but the value was 'test.tnuser02+company@gmail.com'","stack":"    at Context.eval (webpack:///./cypress/e2e/comLogin/companyLogin.cy.js:76:42)","codeFrame":{"line":76,"column":43,"originalFile":"cypress/e2e/comLogin/companyLogin.cy.js","relativeFile":"cypress/e2e/comLogin/companyLogin.cy.js","absoluteFile":"/Users/chaowakrit/Workspace/JobThai/web-jtu-system/cypress/e2e/comLogin/companyLogin.cy.js","frame":"  74 |     }\n  75 |     cy.get(ELEMENT_JOBTHAI.COMPANY_NAME).should('have.value', 'บริษัท แสนแสบ จำกัด') // Company Name\n> 76 |     cy.get(ELEMENT_JOBTHAI.EMAIL_ACCOUNT).should('have.value', 'anuchit@thinknet.co.th') // Email Auth\n     |                                           ^\n  77 |     cy.newTab(ELEMENT_JOBTHAI.LOGO_JOBTHAI)\n  78 |     cy.location('pathname').then((pathname) => decodeURIComponent(pathname)).should('eq', t('companyLogin.URL.HOME'))\n  79 |     cy.get(ELEMENT_JOBTHAI.H_MENU_EMPLOYER).should('contain', `${t('companyLogin.ELEMENT_JOBTHAI.H_MENU_EMPLOYER')} (testuserjtm)`)// .click()","language":"js"}},"timings":{"lifecycle":55,"before each":[{"hookId":"h1","fnDuration":6958,"afterFnDuration":0}],"test":{"fnDuration":21717,"afterFnDuration":129}},"failedFromHookId":null,"wallClockStartedAt":"2022-10-11T03:56:06.733Z","wallClockDuration":28863,"videoTimestamp":46106}]},{"clientId":"r5","state":"passed","displayError":null,"attempts":[{"state":"passed","error":null,"timings":{"lifecycle":42,"before each":[{"hookId":"h1","fnDuration":5766,"afterFnDuration":0}],"test":{"fnDuration":18330,"afterFnDuration":0}},"failedFromHookId":null,"wallClockStartedAt":"2022-10-11T03:56:35.620Z","wallClockDuration":24148,"videoTimestamp":74993}]}],"exception":null,"video":true,"screenshots":[{"screenshotId":"y3k1x","name":null,"testId":"r4","testAttemptIndex":0,"takenAt":"2022-10-11T03:56:35.477Z","height":720,"width":1280}],"reporterStats":{"suites":1,"tests":3,"passes":2,"pending":0,"failures":1,"start":"2022-10-11T03:55:22.330Z","end":"2022-10-11T03:56:59.801Z","duration":97471},"metadata":{"studioCreated":0,"studioExtended":0}},"headers":{"x-route-version":"1","x-cypress-request-attempt":0,"x-os-name":"darwin","x-cypress-version":"10.9.0"}} and token: undefined
> 2022-10-11T03:57:07.511Z cypress:server:api response { screenshotUploadUrls: [ { readUrl: 'http://localhost:9000/sorry-cypress/b32f72c3911426efb9594d5260d7cced.png', uploadUrl: 'http://localhost:9000/sorry-cypress/b32f72c3911426efb9594d5260d7cced.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=MW32h3gd6HvjBEgTRx%2F20221011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221011T035707Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=ca8422550dd23533e0188bc69a2a0a3f13ab5ed21acff570c2461eb57005d9cd', screenshotId: 'y3k1x' } ], videoUploadUrl: 'http://localhost:9000/sorry-cypress/802e076f-9039-49d0-b9c3-9d8ca1e3bf2f.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=MW32h3gd6HvjBEgTRx%2F20221011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221011T035707Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=3e7c55df4bad2c90e3c393290be2fc60ad9624a8fcc5b1cb22f7eeaba993c91c' }
> 2022-10-11T03:57:07.704Z cypress:server:api request to url: PUT http://localhost:1234/instances/802e076f-9039-49d0-b9c3-9d8ca1e3bf2f/stdout with params: {"body":{"stdout":"\n────────────────────────────────────────────────────────────────────────────────────────────────────\n                                                                                                    \n  Running:  companyLogin.cy.js                                                              (1 of 1)\n\n\n\n\n  TH\n  TH\n    ✓ COM-LOGIN-FORM-01 | Login ด้วย Company Account ครั้งแรก (42962ms)\n    ✓ COM-LOGIN-FORM-01 | Login ด้วย Company Account ครั้งแรก (42962ms)\n    1) COM-LOGIN-FORM-02 | Login ด้วย Company Account เก่า\n    1) COM-LOGIN-FORM-02 | Login ด้วย Company Account เก่า\n    ✓ COM-LOGIN-FORM-03 | Login ด้วย Company Account ใหม่ (24139ms)\n    ✓ COM-LOGIN-FORM-03 | Login ด้วย Company Account ใหม่ (24139ms)\n\n\n\n  2 passing (2m)\n  1 failing\n\n  1) TH\n       COM-LOGIN-FORM-02 | Login ด้วย Company Account เก่า:\n\n      Timed out retrying after 4000ms\n      + expected - actual\n\n      -'test.tnuser02+company@gmail.com'\n      +'anuchit@thinknet.co.th'\n      \n      at Context.eval (webpack:///./cypress/e2e/comLogin/companyLogin.cy.js:76:42)\n\n\n\n\n  2 passing (2m)\n  1 failing\n\n  1) TH\n       COM-LOGIN-FORM-02 | Login ด้วย Company Account เก่า:\n\n      Timed out retrying after 4000ms\n      + expected - actual\n\n      -'test.tnuser02+company@gmail.com'\n      +'anuchit@thinknet.co.th'\n      \n      at Context.eval (webpack:///./cypress/e2e/comLogin/companyLogin.cy.js:76:42)\n\n\n\n[mochawesome] Report JSON saved to /Users/chaowakrit/Workspace/JobThai/web-jtu-system/reports/mochawesome/mochawesome_2022-10-11_10-56-59.json\n\n\n  (Results)\n\n  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐\n  │ Tests:        3                                                                                │\n  │ Passing:      2                                                                                │\n  │ Failing:      1                                                                                │\n  │ Pending:      0                                                                                │\n  │ Skipped:      0                                                                                │\n  │ Screenshots:  1                                                                                │\n  │ Video:        true                                                                             │\n  │ Duration:     1 minute, 37 seconds                                                             │\n  │ Spec Ran:     companyLogin.cy.js                                                               │\n  └────────────────────────────────────────────────────────────────────────────────────────────────┘\n\n\n  (Screenshots)\n\n  -  /Users/chaowakrit/Workspace/JobThai/web-jtu-system/cypress/screenshots/companyLo     (1280x720)\n     gin.cy.js/TH -- COM-LOGIN-FORM-02  Login ด้วย Company Account เก่า (failed).png                \n\n\n  (Video)\n\n  -  Started processing:  Compressing to 32 CRF                                                     \n  -  Finished processing: /Users/chaowakrit/Workspace/JobThai/web-jtu-system/cypress/    (6 seconds)\n                          videos/companyLogin.cy.js.mp4                                             \n\n\n  (Uploading Results)\n\n  - Done Uploading (1/2) /Users/chaowakrit/Workspace/JobThai/web-jtu-system/cypress/screenshots/companyLogin.cy.js/TH -- COM-LOGIN-FORM-02  Login ด้วย Company Account เก่า (failed).png\n  - Done Uploading (2/2) /Users/chaowakrit/Workspace/JobThai/web-jtu-system/cypress/videos/companyLogin.cy.js.mp4\n"},"headers":{"x-cypress-request-attempt":0,"x-os-name":"darwin","x-cypress-version":"10.9.0"}} and token: undefined
> 2022-10-11T03:57:07.716Z cypress:server:api response 'OK'
> 2022-10-11T03:57:07.716Z cypress:server:api request to url: POST http://localhost:1234/runs/a37687bfa545382c88837c8f848a2b6d/instances with params: {"body":{"spec":null,"groupId":"test-number-2","machineId":"f05cb56f-a119-479e-8baf-bd356d58bf17","platform":{"osCpus":[{"model":"Apple M1","speed":24,"times":{"user":8530340,"nice":0,"sys":5651600,"idle":41192320,"irq":0}},{"model":"Apple M1","speed":24,"times":{"user":7938260,"nice":0,"sys":5086110,"idle":42348210,"irq":0}},{"model":"Apple M1","speed":24,"times":{"user":7073290,"nice":0,"sys":4443680,"idle":43855640,"irq":0}},{"model":"Apple M1","speed":24,"times":{"user":6369240,"nice":0,"sys":3983550,"idle":45019850,"irq":0}},{"model":"Apple M1","speed":24,"times":{"user":4394320,"nice":0,"sys":1811920,"idle":49166390,"irq":0}},{"model":"Apple M1","speed":24,"times":{"user":3264830,"nice":0,"sys":1240080,"idle":50867700,"irq":0}},{"model":"Apple M1","speed":24,"times":{"user":2546250,"nice":0,"sys":812360,"idle":52014010,"irq":0}},{"model":"Apple M1","speed":24,"times":{"user":2104940,"nice":0,"sys":584830,"idle":52682840,"irq":0}}],"osName":"darwin","osMemory":{"free":158892032,"total":17179869184},"osVersion":"20.3.0","browserName":"Electron","browserVersion":"102.0.5005.148"}},"headers":{"x-route-version":"5","x-cypress-run-id":"a37687bfa545382c88837c8f848a2b6d","x-cypress-request-attempt":0,"x-os-name":"darwin","x-cypress-version":"10.9.0"}} and token: undefined
> 2022-10-11T03:57:07.738Z cypress:server:api response { spec: null, instanceId: null, claimedInstances: 0, totalInstances: 1 }
> ```
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/15319932/194995053-ad43c89e-1cac-4b42-b379-4fdf8b0d2873.png">
> 
> <img alt="image" width="590" src="https://user-images.githubusercontent.com/15319932/194995112-e05d4c76-d4ee-4251-9031-2ac0ce7abf20.png">
> 
> <img alt="image" width="781" src="https://user-images.githubusercontent.com/15319932/194995146-d0a2087f-1dcc-4286-9d4d-7a35c4167f79.png">
> 
> ## Environment
> * Mac OSX
> * sorry-cypress version: `2.4.2`
> * cypress version: `10.9.0`
> * platform: `docker`
> * service: `dashboard`

Hi, just change access to bucket in minio console from "custom" to public.

![Снимок экрана от 2022-10-17 14-15-08](https://user-images.githubusercontent.com/77897694/196163809-62a3066d-f655-4ba4-8692-207e34a1bacb.png)

**Comment by chaowakrit** [comment]
Thank you
