### ISSUE TITLE
/instances/:instanceId/results API get 500 error code

### ISSUE THREAD

**Issue by renling-nd** [sorry-cypress/sorry-cypress#754]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `latest(docker image: agoldis/sorry-cypress-director:latest)`
  - cypress version: `7.5.0`
  - cy2 version: `1.3.0`
  - platform: `k8s `
  - service: `api | director |`

```

</details>

### Describe the bug

Hi All.
My question is: when the cypress case is executed in parallel on multiple machines,  some machines call this API /instances/:instanceId/results has 500 error code，I'm not sure if sorry-cypress bug , the log is as follows:
`{"level":30,"time":1678159711717,"req":{"id":6,"method":"POST","url":"/instances/98f46f81-cd9b-4a67-b15f-0bf886d6ed4f/results","query":{},"params":{},"headers":{"x-route-version":"1","x-cypress-request-attempt":"4","x-os-name":"linux","x-cypress-version":"7.5.0","host":"cypress-automation-director.cypress-automation.svc.cluster.local:1234","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json","content-length":"21479","connection":"close"},"remoteAddress":"::ffff:10.103.0.4","remotePort":40292},"res":{"statusCode":500,"headers":{"x-powered-by":"Express","content-type":"text/html; charset=utf-8","content-length":"89","etag":"W/\"59-JMJsr+GKg9vLr9EtbregGDl0ppM\""}},"err":{"type":"Error","message":"failed with status code 500","stack":"Error: failed with status code 500\n    at ServerResponse.onResFinished (/app/node_modules/pino-http/logger.js:74:38)\n    at ServerResponse.emit (node:events:525:35)\n    at onFinish (node:_http_outgoing:950:10)\n    at callback (node:internal/streams/writable:554:21)\n    at afterWrite (node:internal/streams/writable:499:5)\n    at afterWriteTick (node:internal/streams/writable:486:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"},"responseTime":2,"msg":"request errored"}
`
If it's not a bug please let me know what's going on and how to fix it.
Thanks for any help!

### Expected behavior

can work normally

### Reproduction steps

We have more than 1000 cases running on 10 CI machines at the same time, and occasionally several machines will report this error

### Full log and debug output

<details>

```
 √ : [edme-gbl-auto-poweruser] / ⨠ kubectl logs cypress-automation-director-777cd96c79-2cc2v cypress-automation-director
2023-03-07T03:21:20: PM2 log: Launching in no daemon mode
2023-03-07T03:21:20: PM2 log: App [dist:0] starting in -fork mode-
2023-03-07T03:21:20: PM2 log: App [dist:0] online
{"level":30,"time":1678159281286,"msg":"🔧 Director execution driver: in-memory"}
{"level":30,"time":1678159281287,"msg":"🎧 Initializing listeners for hooks..."}
{"level":30,"time":1678159281289,"msg":"🚀 Director service is ready at http://0.0.0.0:1234/..."}
{"level":30,"time":1678159311677,"requestId":"34a288c0-3e88-4364-93e8-ab26e596f2db","msg":"[hooks] Hooks set for project cypress-automation"}
{"level":30,"time":1678159311681,"req":{"id":1,"method":"POST","url":"/hooks","query":{},"params":{},"headers":{"accept":"application/json, text/plain, */*","authorization":"Basic YXV0by50ZXN0cmFpbEBlZG1vZG93b3JsZC5jb206Z2p6M1pQYTNZa1psa1hiREJ4U04tYUVscUYwY1ZSSVkvUWVJVnVwUjQ","content-type":"application/json;charset=utf-8","user-agent":"axios/0.21.1","content-length":"175","host":"localhost:1234","connection":"close"},"remoteAddress":"::ffff:127.0.0.1","remotePort":35418},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","content-type":"text/html; charset=utf-8","content-length":"43","etag":"W/\"2b-/SCy/tQWT/Fqcgqb26qJIktkRJA\""}},"responseTime":14,"msg":"request completed"}
{"level":30,"time":1678159501631,"requestId":"a15e9218-9cf2-4fc5-9453-7b85e2467200","instanceId":"98f46f81-cd9b-4a67-b15f-0bf886d6ed4f","stats":{"suites":1,"tests":8,"passes":0,"pending":4,"skipped":0,"failures":4,"wallClockStartedAt":"2023-03-07T03:17:43.162Z","wallClockEndedAt":"2023-03-07T03:23:13.813Z","wallClockDuration":330651},"tests":[{"clientId":"r3","state":"failed","displayError":"AssertionError: Timed out retrying after 30000ms: Expected to find element: `.qa-test-tdKey-CURRENT_INSTITUTION_NAME-0`, but never found it.\n    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142497:25)\n    at $Cy.ensureElExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142515:12)\n    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131472:23)\n    at onFailFn (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131510:9)\n    at tryCatcher (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:10798:23)\n    at Promise._settlePromiseFromHandler (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8733:31)\n    at Promise._settlePromise (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8790:18)\n    at Promise._settlePromise0 (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8835:10)\n    at Promise._settlePromises (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8911:18)\n    at _drainQueueStep (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5505:12)\n    at _drainQueue (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5498:9)\n    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5514:5)\n    at Async.drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5384:14)","attempts":[{"state":"failed","error":{"name":"AssertionError","message":"Timed out retrying after 30000ms: Expected to find element: `.qa-test-tdKey-CURRENT_INSTITUTION_NAME-0`, but never found it.","stack":"    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142497:25)\n    at $Cy.ensureElExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142515:12)\n    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131472:23)\n    at onFailFn (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131510:9)\n    at tryCatcher (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:10798:23)\n    at Promise._settlePromiseFromHandler (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8733:31)\n    at Promise._settlePromise (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8790:18)\n    at Promise._settlePromise0 (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8835:10)\n    at Promise._settlePromises (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8911:18)\n    at _drainQueueStep (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5505:12)\n    at _drainQueue (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5498:9)\n    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5514:5)\n    at Async.drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5384:14)"},"timings":{"lifecycle":19,"before all":[{"hookId":"h6","fnDuration":3,"afterFnDuration":0}],"before each":[{"hookId":"h1","fnDuration":15,"afterFnDuration":0},{"hookId":"h2","fnDuration":91,"afterFnDuration":1},{"hookId":"h7","fnDuration":0,"afterFnDuration":0}],"test":{"fnDuration":45441,"afterFnDuration":374},"after each":[{"hookId":"h5","fnDuration":30,"afterFnDuration":1}]},"failedFromHookId":null,"wallClockStartedAt":"2023-03-07T03:17:43.172Z","wallClockDuration":45983,"videoTimestamp":23344}]},{"clientId":"r4","state":"pending","displayError":"[object Object]\nFrom Your Spec Code:\n    at Context.eval (https://new.qa.mes1.edme.be/__cypress/tests?p=cypress/integration/ADT/insight/score_analysis/score_analysis.feature:83988:10)","attempts":[{"state":"pending","error":{"name":"CypressError","message":"sync skip; aborting execution","stack":"    at Context.eval (https://new.qa.mes1.edme.be/__cypress/tests?p=cypress/integration/ADT/insight/score_analysis/score_analysis.feature:83988:10)","codeFrame":{"line":71,"column":1,"originalFile":"node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js","relativeFile":"node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js","absoluteFile":"/node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js","frame":"  69 |         .then(() => state.onFinishScenario(scenario))\n  70 |         // eslint-disable-next-line func-names\n> 71 |         .then(function () {\n     | ^\n  72 |           return this.skip();\n  73 |         });\n  74 |     });","language":"js"}},"timings":{"lifecycle":85,"before each":[{"hookId":"h1","fnDuration":8,"afterFnDuration":0},{"hookId":"h2","fnDuration":71,"afterFnDuration":0},{"hookId":"h7","fnDuration":0,"afterFnDuration":0}],"test":{"fnDuration":3,"afterFnDuration":0},"after each":[{"hookId":"h5","fnDuration":9,"afterFnDuration":0}]},"failedFromHookId":null,"wallClockStartedAt":"2023-03-07T03:18:29.161Z","wallClockDuration":null,"videoTimestamp":69333}]},{"clientId":"r5","state":"failed","displayError":"AssertionError: Timed out retrying after 30000ms: Expected to find element: `.qa-test-tdKey-CURRENT_INSTITUTION_NAME-0`, but never found it.\n    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142497:25)\n    at $Cy.ensureElExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142515:12)\n    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131472:23)\n    at onFailFn (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131510:9)\n    at tryCatcher (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:10798:23)\n    at Promise._settlePromiseFromHandler (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8733:31)\n    at Promise._settlePromise (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8790:18)\n    at Promise._settlePromise0 (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8835:10)\n    at Promise._settlePromises (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8911:18)\n    at _drainQueueStep (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5505:12)\n    at _drainQueue (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5498:9)\n    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5514:5)\n    at Async.drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5384:14)","attempts":[{"state":"failed","error":{"name":"AssertionError","message":"Timed out retrying after 30000ms: Expected to find element: `.qa-test-tdKey-CURRENT_INSTITUTION_NAME-0`, but never found it.","stack":"    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142497:25)\n    at $Cy.ensureElExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142515:12)\n    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131472:23)\n    at onFailFn (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131510:9)\n    at tryCatcher (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:10798:23)\n    at Promise._settlePromiseFromHandler (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8733:31)\n    at Promise._settlePromise (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8790:18)\n    at Promise._settlePromise0 (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8835:10)\n    at Promise._settlePromises (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8911:18)\n    at _drainQueueStep (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5505:12)\n    at _drainQueue (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5498:9)\n    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5514:5)\n    at Async.drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5384:14)"},"timings":{"lifecycle":68,"before each":[{"hookId":"h1","fnDuration":19,"afterFnDuration":0},{"hookId":"h2","fnDuration":195,"afterFnDuration":0},{"hookId":"h7","fnDuration":1,"afterFnDuration":0}],"test":{"fnDuration":106861,"afterFnDuration":773},"after each":[{"hookId":"h5","fnDuration":26,"afterFnDuration":1}]},"failedFromHookId":null,"wallClockStartedAt":"2023-03-07T03:18:29.376Z","wallClockDuration":107988,"videoTimestamp":69548}]},{"clientId":"r6","state":"failed","displayError":"AssertionError: Timed out retrying after 30000ms: Expected to find element: `.qa-test-tdKey-CURRENT_INSTITUTION_NAME-0`, but never found it.\n    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142497:25)\n    at $Cy.ensureElExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142515:12)\n    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131472:23)\n    at onFailFn (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131510:9)\n    at tryCatcher (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:10798:23)\n    at Promise._settlePromiseFromHandler (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8733:31)\n    at Promise._settlePromise (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8790:18)\n    at Promise._settlePromise0 (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8835:10)\n    at Promise._settlePromises (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8911:18)\n    at _drainQueueStep (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5505:12)\n    at _drainQueue (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5498:9)\n    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5514:5)\n    at Async.drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5384:14)","attempts":[{"state":"failed","error":{"name":"AssertionError","message":"Timed out retrying after 30000ms: Expected to find element: `.qa-test-tdKey-CURRENT_INSTITUTION_NAME-0`, but never found it.","stack":"    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142497:25)\n    at $Cy.ensureElExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142515:12)\n    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131472:23)\n    at onFailFn (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131510:9)\n    at tryCatcher (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:10798:23)\n    at Promise._settlePromiseFromHandler (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8733:31)\n    at Promise._settlePromise (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8790:18)\n    at Promise._settlePromise0 (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8835:10)\n    at Promise._settlePromises (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8911:18)\n    at _drainQueueStep (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5505:12)\n    at _drainQueue (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5498:9)\n    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5514:5)\n    at Async.drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5384:14)"},"timings":{"lifecycle":306,"before each":[{"hookId":"h1","fnDuration":8,"afterFnDuration":0},{"hookId":"h2","fnDuration":68,"afterFnDuration":0},{"hookId":"h7","fnDuration":0,"afterFnDuration":0}],"test":{"fnDuration":106554,"afterFnDuration":806},"after each":[{"hookId":"h5","fnDuration":14,"afterFnDuration":0}]},"failedFromHookId":null,"wallClockStartedAt":"2023-03-07T03:20:17.369Z","wallClockDuration":107786,"videoTimestamp":177541}]},{"clientId":"r7","state":"pending","displayError":"[object Object]\nFrom Your Spec Code:\n    at Context.eval (https://new.qa.mes1.edme.be/__cypress/tests?p=cypress/integration/ADT/insight/score_analysis/score_analysis.feature:83988:10)","attempts":[{"state":"pending","error":{"name":"CypressError","message":"sync skip; aborting execution","stack":"    at Context.eval (https://new.qa.mes1.edme.be/__cypress/tests?p=cypress/integration/ADT/insight/score_analysis/score_analysis.feature:83988:10)","codeFrame":{"line":71,"column":1,"originalFile":"node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js","relativeFile":"node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js","absoluteFile":"/node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js","frame":"  69 |         .then(() => state.onFinishScenario(scenario))\n  70 |         // eslint-disable-next-line func-names\n> 71 |         .then(function () {\n     | ^\n  72 |           return this.skip();\n  73 |         });\n  74 |     });","language":"js"}},"timings":{"lifecycle":296,"before each":[{"hookId":"h1","fnDuration":9,"afterFnDuration":0},{"hookId":"h2","fnDuration":80,"afterFnDuration":0},{"hookId":"h7","fnDuration":1,"afterFnDuration":0}],"test":{"fnDuration":5,"afterFnDuration":0},"after each":[{"hookId":"h5","fnDuration":299,"afterFnDuration":0}]},"failedFromHookId":null,"wallClockStartedAt":"2023-03-07T03:22:05.160Z","wallClockDuration":null,"videoTimestamp":285332}]},{"clientId":"r8","state":"pending","displayError":"[object Object]\nFrom Your Spec Code:\n    at Context.eval (https://new.qa.mes1.edme.be/__cypress/tests?p=cypress/integration/ADT/insight/score_analysis/score_analysis.feature:83988:10)","attempts":[{"state":"pending","error":{"name":"CypressError","message":"sync skip; aborting execution","stack":"    at Context.eval (https://new.qa.mes1.edme.be/__cypress/tests?p=cypress/integration/ADT/insight/score_analysis/score_analysis.feature:83988:10)","codeFrame":{"line":71,"column":1,"originalFile":"node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js","relativeFile":"node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js","absoluteFile":"/node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js","frame":"  69 |         .then(() => state.onFinishScenario(scenario))\n  70 |         // eslint-disable-next-line func-names\n> 71 |         .then(function () {\n     | ^\n  72 |           return this.skip();\n  73 |         });\n  74 |     });","language":"js"}},"timings":{"lifecycle":214,"before each":[{"hookId":"h1","fnDuration":5,"afterFnDuration":1},{"hookId":"h2","fnDuration":63,"afterFnDuration":0},{"hookId":"h7","fnDuration":0,"afterFnDuration":0}],"test":{"fnDuration":2,"afterFnDuration":0},"after each":[{"hookId":"h5","fnDuration":232,"afterFnDuration":1}]},"failedFromHookId":null,"wallClockStartedAt":"2023-03-07T03:22:05.856Z","wallClockDuration":null,"videoTimestamp":286028}]},{"clientId":"r9","state":"pending","displayError":"[object Object]\nFrom Your Spec Code:\n    at Context.eval (https://new.qa.mes1.edme.be/__cypress/tests?p=cypress/integration/ADT/insight/score_analysis/score_analysis.feature:83988:10)","attempts":[{"state":"pending","error":{"name":"CypressError","message":"sync skip; aborting execution","stack":"    at Context.eval (https://new.qa.mes1.edme.be/__cypress/tests?p=cypress/integration/ADT/insight/score_analysis/score_analysis.feature:83988:10)","codeFrame":{"line":71,"column":1,"originalFile":"node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js","relativeFile":"node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js","absoluteFile":"/node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js","frame":"  69 |         .then(() => state.onFinishScenario(scenario))\n  70 |         // eslint-disable-next-line func-names\n> 71 |         .then(function () {\n     | ^\n  72 |           return this.skip();\n  73 |         });\n  74 |     });","language":"js"}},"timings":{"lifecycle":219,"before each":[{"hookId":"h1","fnDuration":5,"afterFnDuration":0},{"hookId":"h2","fnDuration":56,"afterFnDuration":0},{"hookId":"h7","fnDuration":0,"afterFnDuration":0}],"test":{"fnDuration":1,"afterFnDuration":0},"after each":[{"hookId":"h5","fnDuration":27,"afterFnDuration":0}]},"failedFromHookId":null,"wallClockStartedAt":"2023-03-07T03:22:06.384Z","wallClockDuration":null,"videoTimestamp":286556}]},{"clientId":"r10","state":"failed","displayError":"AssertionError: Timed out retrying after 30000ms: Expected to find element: `.qa-test-tdKey-CURRENT_INSTITUTION_NAME-0`, but never found it.\n    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142497:25)\n    at $Cy.ensureElExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142515:12)\n    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131472:23)\n    at onFailFn (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131510:9)\n    at tryCatcher (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:10798:23)\n    at Promise._settlePromiseFromHandler (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8733:31)\n    at Promise._settlePromise (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8790:18)\n    at Promise._settlePromise0 (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8835:10)\n    at Promise._settlePromises (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8911:18)\n    at _drainQueueStep (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5505:12)\n    at _drainQueue (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5498:9)\n    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5514:5)\n    at Async.drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5384:14)","attempts":[{"state":"failed","error":{"name":"AssertionError","message":"Timed out retrying after 30000ms: Expected to find element: `.qa-test-tdKey-CURRENT_INSTITUTION_NAME-0`, but never found it.","stack":"    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142497:25)\n    at $Cy.ensureElExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:142515:12)\n    at ensureExistence (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131472:23)\n    at onFailFn (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:131510:9)\n    at tryCatcher (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:10798:23)\n    at Promise._settlePromiseFromHandler (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8733:31)\n    at Promise._settlePromise (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8790:18)\n    at Promise._settlePromise0 (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8835:10)\n    at Promise._settlePromises (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:8911:18)\n    at _drainQueueStep (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5505:12)\n    at _drainQueue (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5498:9)\n    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5514:5)\n    at Async.drainQueues (https://new.qa.mes1.edme.be/__cypress/runner/cypress_runner.js:5384:14)"},"timings":{"lifecycle":215,"before each":[{"hookId":"h1","fnDuration":8,"afterFnDuration":0},{"hookId":"h2","fnDuration":61,"afterFnDuration":0},{"hookId":"h7","fnDuration":0,"afterFnDuration":0}],"test":{"fnDuration":65700,"afterFnDuration":580},"after each":[{"hookId":"h5","fnDuration":35,"afterFnDuration":0}],"after all":[{"hookId":"h8","fnDuration":0,"afterFnDuration":0},{"hookId":"h3","fnDuration":5,"afterFnDuration":0},{"hookId":"h4","fnDuration":253,"afterFnDuration":0}]},"failedFromHookId":null,"wallClockStartedAt":"2023-03-07T03:22:06.944Z","wallClockDuration":66866,"videoTimestamp":287116}]}],"exception":null,"video":true,"screenshots":[{"screenshotId":"7tcsc","name":null,"testId":"r3","testAttemptIndex":0,"takenAt":"2023-03-07T03:18:28.754Z","height":1080,"width":1920},{"screenshotId":"werpu","name":null,"testId":"r5","testAttemptIndex":0,"takenAt":"2023-03-07T03:20:16.533Z","height":1080,"width":1920},{"screenshotId":"0nopz","name":null,"testId":"r6","testAttemptIndex":0,"takenAt":"2023-03-07T03:22:04.314Z","height":1080,"width":1920},{"screenshotId":"8afcb","name":null,"testId":"r10","testAttemptIndex":0,"takenAt":"2023-03-07T03:23:12.935Z","height":1080,"width":1920}],"reporterStats":{"suites":1,"tests":8,"passes":0,"pending":4,"failures":4,"start":"2023-03-07T03:17:43.167Z","end":"2023-03-07T03:23:14.123Z","duration":330956},"metadata":{"studioCreated":0,"studioExtended":0},"msg":"Received instance results"}
{"level":50,"time":1678159501632,"requestId":"a15e9218-9cf2-4fc5-9453-7b85e2467200","error":{"type":"AppError","message":"AppError","stack":"Error: AppError\n    at Object.updateInstanceResults (/app/packages/director/src/execution/in-memory.ts:214:11)\n    at updateInstanceResults (/app/packages/director/src/api/instances.ts:124:42)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at /app/packages/director/src/lib/express.ts:10:5","code":"INSTANCE_NOT_EXIST"}}
{"level":30,"time":1678159501653,"req":{"id":2,"method":"POST","url":"/instances/98f46f81-cd9b-4a67-b15f-0bf886d6ed4f/results","query":{},"params":{},"headers":{"x-route-version":"1","x-cypress-request-attempt":"0","x-os-name":"linux","x-cypress-version":"7.5.0","host":"cypress-automation-director.cypress-automation.svc.cluster.local:1234","accept-encoding":"gzip, deflate","accept":"application/json","content-type":"application/json","content-length":"21479","connection":"close"},"remoteAddress":"::ffff:10.103.0.4","remotePort":51992},"res":{"statusCode":500,"headers":{"x-powered-by":"Express","content-type":"text/html; charset=utf-8","content-length":"89","etag":"W/\"59-JMJsr+GKg9vLr9EtbregGDl0ppM\""}},"err":{"type":"Error","message":"failed with status code 500","stack":"Error: failed with status code 500\n    at ServerResponse.onResFinished (/app/node_modules/pino-http/logger.js:74:38)\n    at ServerResponse.emit (node:events:525:35)\n    at onFinish (node:_http_outgoing:950:10)\n    at callback (node:internal/streams/writable:554:21)\n    at afterWrite (node:internal/streams/writable:499:5)\n    at afterWriteTick (node:internal/streams/writable:486:10)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"},"responseTime":23,"msg":"request errored"}

```

</details>

**Comment by mirobo** [comment]
Does this error result in "The server's response was: StatusCodeError: 500 - "Unexpected error from sorry-cypress director service. Check the service logs for details." when executing the tests with "cypress run"?
I'm having similar issues but haven't found a way to reproduce it (I use Cypress 10.7.0 with Module API and sorry-cypress 2.1.3

**Comment by renling-nd** [comment]
yes, executing the tests with "cypress run",
(I use Cypress 7.5.0 and sorry-cypress 2.5.3)

**Comment by agoldis** [comment]
...most likely because you're using in-memory director and it restarts, wiping all in-memory data , then it tries to update non-existing spec and fails.

**Comment by renling-nd** [comment]
Is it possible to upgrade to full setup（using mongodb） to solve this problem?

**Comment by agoldis** [comment]
it is up to you, but in theory it would solve the problem with restarts

**Comment by renling-nd** [comment]
OK，I will try it on Full Setup and check if this problem still occurs
