### ISSUE TITLE
director becomes unresponsive after mongo blip

### ISSUE THREAD

**Issue by joe-carpenter** [sorry-cypress/sorry-cypress#90]
Hi!

Firstly, cool project - thanks a million!! 

We've been running `sorry-cypress` for maybe a couple of months now, in a very lightweight fashion on a Kubernetes platform, and we've been making very heavy use of it.

MongoDB (also running on Kubernetes) appears to have died and the pods were recreated - looks like we lost both primary and secondary but not the arbiter.

Logs from director start looking unhealthy at this point (and continue to log lots of `UnhandledPromiseRejectionWarning` until `director` was restarted):

```
...
>> Received instance result { instanceId: 'b7384ffa-5bdc-4367-a9d7-7a5dbaffa2b0' }
(node:27) UnhandledPromiseRejectionWarning: MongoTimeoutError: failed to reconnect after 30 attempts with interval 1000 ms
    at Timeout.<anonymous> (/app/node_modules/mongodb/lib/core/connection/pool.js:320:21)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>> Received instance result { instanceId: 'f642e351-1397-4bad-bed2-5009efba8c34' }
(node:27) UnhandledPromiseRejectionWarning: MongoError: server instance pool was destroyed
    at basicWriteValidations (/app/node_modules/mongodb/lib/core/topologies/server.js:574:41)
    at Server.update (/app/node_modules/mongodb/lib/core/topologies/server.js:719:16)
    at Server.update (/app/node_modules/mongodb/lib/topologies/topology_base.js:306:25)
    at updateDocuments (/app/node_modules/mongodb/lib/operations/common_functions.js:370:19)
    at UpdateOneOperation.execute (/app/node_modules/mongodb/lib/operations/update_one.js:24:5)
    at executeOperation (/app/node_modules/mongodb/lib/operations/execute_operation.js:77:17)
    at Collection.updateOne (/app/node_modules/mongodb/lib/collection.js:765:10)
    at Object.setInstanceResults (/app/dist/execution/mongo/instances/instance.model.js:48:66)
    at app.put (/app/dist/app.js:110:25)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
...
```

Most of the solution is to have a more stable MongoDB! But was wondering if it was possible to detect this scenario and recover from it without a manual restart? Or would this have recovered eventually anyway?

The perspective of the client is:
```
[2020-07-20T14:55:23.332Z] We encountered an unexpected error talking to our servers.
[2020-07-20T14:55:23.332Z] 
[2020-07-20T14:55:23.332Z] We will retry 3 more times in 30 seconds...
[2020-07-20T14:55:23.332Z] 
[2020-07-20T14:55:23.332Z] The server's response was:
[2020-07-20T14:55:23.332Z] 
[2020-07-20T14:55:23.332Z] RequestError: Error: ESOCKETTIMEDOUT
[2020-07-20T14:56:59.732Z] We encountered an unexpected error talking to our servers.
```

... and when I tried to go to the dashboard I got a similar socket timeout on a call to the api

**Comment by agoldis** [comment]
Thanks for reporting that. I will be honest with you, just restarting the director would be the most efficient approach given your use case. I will look into wrapping `director` in forever or similar - that shouldn't be too difficult.

**Comment by ThomasPause** [comment]
Hi, anything new with that issue? having the same challenge with that and restarting the director is not the best way in everydays usage ;)
Btw: very very nice app, i love it!!!

Also running on K8S with mongoDB and Minio

**Comment by ThomasPause** [comment]
Problem is gone when using dummy driver for screenshots. Seems to be Minio connection issue. I´m going to dive deeper into it and report it here.
Also have problems with showing images/videos, but I think that´s my fault. ;)

**Comment by BHunter2889** [comment]
@ThomasPause any updates? Also having similar issues.

**Comment by ThomasPause** [comment]
@BHunter2889 no updates until now.

**Comment by nguyenhoaibao** [comment]
If running in a Kubernetes cluster, I think we can set `NODE_OPTIONS=--unhandle-restrictions=strict` to let the node server crash, and then Kubernetes will restart it automatically.

**Comment by agoldis** [comment]
Resolved in v2
